spring.application.name=system

# SECURITY CONFIG
app.cookie.secure=false
spring.security.user.name=test
spring.security.user.password=testing123

# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/Bodegaz
spring.datasource.username=postgres
spring.datasource.password=moshiroshiina24
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kieraldwinibay24@gmail.com
spring.mail.password=igeqaeiptevamiyn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#JWT CONFIG
app.jwt.secret=e/VeFilzblLzzJmcO122EFhQd7EJYqI4sOs2luD3qBk=
app.jwt.expiration=3600000
app.jwt.refresh-expiration=86400000
